baseurl = "https://rudy-kh.com"
languageCode = "en"
title = "Rudy Khalil"
theme = "hemingway2"
disqusShortname = "rudy-kh"
googleAnalytics = ""
description = "My Technical Blog"
keywords = ["keyword1", "keyword2"]

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["java", "python"]

[[params.social]]
url = "https://github.com/rudy-kh"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/_rudyKh"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://www.linkedin.com/in/rudy-khalil-599bb64b/"
fa_icon = "fa-linkedin-square"